"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {Archive,ArrowLeft,ChevronDown,Clock3,FileText,Folder,Inbox,LogOut,Mail,MailOpen,Menu,MoreHorizontal,Paperclip,PenLine,Plus,RefreshCw,Reply,Search,Send,Settings2,Star,Trash2,X} from "lucide-react";
type Box={id:string,name:string,role?:string,sortOrder?:number,totalEmails?:number,unreadEmails?:number};
type Addr={name?:string,email:string};
type MailItem={id:string,mailboxIds:Record<string,boolean>,keywords:Record<string,boolean>,from?:Addr[],to?:Addr[],subject?:string,receivedAt?:string,preview?:string,hasAttachment?:boolean,size?:number};
type MailData={username?:string,mailboxes:Box[],emails:MailItem[]};
export default function Home(){
 const router=useRouter(),fileRef=useRef<HTMLInputElement>(null);
 const [data,setData]=useState<MailData|null>(null),[selected,setSelected]=useState<MailItem|null>(null),[full,setFull]=useState<any>(null);
 const [box,setBox]=useState(""),[query,setQuery]=useState(""),[attachmentOnly,setAttachmentOnly]=useState(false),[mobile,setMobile]=useState(false),[readerOpen,setReaderOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [compose,setCompose]=useState(false),[to,setTo]=useState(""),[cc,setCc]=useState(""),[bcc,setBcc]=useState(""),[showExtra,setShowExtra]=useState(false),[subject,setSubject]=useState(""),[text,setText]=useState("");
 const [sending,setSending]=useState(false),[sendError,setSendError]=useState(""),[attachments,setAttachments]=useState<any[]>([]),[uploading,setUploading]=useState(false);
 async function load(keep=true){setLoading(true);setError("");try{const r=await fetch("/api/mail/data",{cache:"no-store"});if(r.status===401){router.replace("/login");return}const d=await r.json();if(!r.ok)throw new Error(d.error||"Ошибка загрузки");setData(d);if(!box){const inbox=d.mailboxes.find((x:Box)=>x.role==="inbox")||d.mailboxes[0];setBox(inbox?.id||"")}if(keep&&selected){const fresh=d.emails.find((x:MailItem)=>x.id===selected.id);if(fresh)setSelected(fresh)}}catch(e:any){setError(e.message||"Нет связи с сервером")}finally{setLoading(false)}}
 useEffect(()=>{load(false)},[]);
 const currentBox=data?.mailboxes.find(x=>x.id===box);
 const emails=useMemo(()=>{if(!data)return[];const q=query.trim().toLowerCase();return data.emails.filter(m=>(!box||m.mailboxIds?.[box])&&(!attachmentOnly||m.hasAttachment)&&(!q||(m.from?.[0]?.name+" "+m.from?.[0]?.email+" "+m.to?.[0]?.email+" "+m.subject+" "+m.preview).toLowerCase().includes(q)))},[data,box,query,attachmentOnly]);
 useEffect(()=>{if(selected&&!emails.some(x=>x.id===selected.id)){setSelected(null);setFull(null)}},[box]);
 useEffect(()=>{if(!selected)return;setFull(null);fetch("/api/mail/message?id="+encodeURIComponent(selected.id)).then(r=>r.json()).then(setFull)},[selected?.id]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/login")}
 async function action(action:string,id=selected?.id){if(!id)return;const r=await fetch("/api/mail/action",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action})});if(!r.ok)return;await load(false);if(["trash","archive","restore","delete"].includes(action)){setSelected(null);setFull(null);setReaderOpen(false)}}
 function openMail(m:MailItem){setSelected(m);setReaderOpen(true);if(!m.keywords?.["$seen"])action("read",m.id)}
 function resetCompose(){setTo("");setCc("");setBcc("");setSubject("");setText("");setAttachments([]);setSendError("");setShowExtra(false)}
 function newMail(){resetCompose();setCompose(true)}
 function reply(forward=false){if(!selected)return;resetCompose();const a=selected.from?.[0];setTo(forward?"":a?.email||"");setSubject((forward?"Fwd: ":"Re: ")+(selected.subject||"").replace(/^(Re: |Fwd: )/i,""));setText(forward?"\n\n---------- Пересланное сообщение ----------\nОт: "+(a?.name||a?.email||"")+" <"+(a?.email||"")+">\nДата: "+(selected.receivedAt?new Date(selected.receivedAt).toLocaleString("ru-RU"):"")+"\nТема: "+(selected.subject||"")+"\n\n"+plainBody():"\n\n");setCompose(true)}
 async function addFiles(files:FileList|null){if(!files?.length)return;setUploading(true);setSendError("");try{for(const file of Array.from(files)){const fd=new FormData();fd.append("file",file);const r=await fetch("/api/mail/attachment",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||"Ошибка загрузки");setAttachments(a=>[...a,d])}}catch(e:any){setSendError(e.message||"Ошибка загрузки")}finally{setUploading(false);if(fileRef.current)fileRef.current.value=""}}
 async function sendMail(){setSendError("");setSending(true);try{const r=await fetch("/api/mail/send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({to,cc,bcc,subject,text,attachments})});const d=await r.json();if(!r.ok){setSendError(d.error||"Ошибка отправки");return}setCompose(false);resetCompose();await load(false)}catch{setSendError("Нет связи с сервером")}finally{setSending(false)}}
 function boxLabel(m:Box){const labels:Record<string,string>={inbox:"Входящие",sent:"Отправленные",drafts:"Черновики",trash:"Корзина",archive:"Архив",junk:"Спам"};return (m.role&&labels[m.role])||m.name}\n function icon(role?:string){if(role==="inbox")return Inbox;if(role==="sent")return Send;if(role==="drafts")return FileText;if(role==="trash")return Trash2;if(role==="archive")return Archive;return Folder}
 function plainBody(){if(!full)return selected?.preview||"";for(const p of full.textBody||[]){const v=full.bodyValues?.[p.partId]?.value;if(v)return v}for(const p of full.htmlBody||[]){const v=full.bodyValues?.[p.partId]?.value;if(v)return v.replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]*>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/\s{3,}/g," ").trim()}return full.preview||selected?.preview||""}
 const inTrash=currentBox?.role==="trash";
 return <main className="shell">
  <header className="topbar"><button className="mobileMenu" onClick={()=>setMobile(!mobile)}><Menu/></button><div className="brand"><span className="brandMark">S</span><div><b>SchoolBook</b><small>Mail</small></div></div><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск в почте…"/>{query&&<button onClick={()=>setQuery("")}><X/></button>}</div><button className="refresh" onClick={()=>load()} title="Обновить"><RefreshCw className={loading?"spin":""}/></button><div className="account"><span className="avatar">{(data?.username||"S")[0].toUpperCase()}</span><div><b>{data?.username?.split("@")[0]||"Почта"}</b><small>{data?.username||"Загрузка…"}</small></div><ChevronDown/></div></header>
  <div className="workspace"><aside className={mobile?"open":""}><button className="compose" onClick={newMail}><PenLine/>Написать письмо</button><nav>{[...(data?.mailboxes||[])].sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0)).map(m=>{const Icon=icon(m.role);return <button key={m.id} onClick={()=>{setBox(m.id);setSelected(null);setReaderOpen(false);setMobile(false)}} className={box===m.id?"active":""}><Icon/><span>{boxLabel(m)}</span>{!!m.unreadEmails&&<em>{m.unreadEmails}</em>}</button>})}</nav><div className="sectionTitle"><span>Папки</span></div><div className="asideBottom"><button className="settings"><Settings2/>Настройки</button><button className="settings" onClick={logout}><LogOut/>Выйти</button></div></aside>
  {mobile&&<div className="mobileScrim" onClick={()=>setMobile(false)}/>}
  <section className="list"><div className="listHead"><div><h1>{currentBox?boxLabel(currentBox):"Почта"}</h1><span>{currentBox?.unreadEmails||0} непрочитанных</span></div><button className="sortButton">Сначала новые <ChevronDown/></button></div><div className="tabs"><button className={!attachmentOnly?"active":""} onClick={()=>setAttachmentOnly(false)}>Все</button><button className={attachmentOnly?"active":""} onClick={()=>setAttachmentOnly(true)}>С вложениями</button></div><div className="messages">{error&&<div className="empty error">{error}<button onClick={()=>load()}>Повторить</button></div>}{loading&&!data&&<div className="empty">Загрузка почты…</div>}{data&&!error&&emails.length===0&&<div className="empty"><Mail/><b>Здесь пока пусто</b><span>Письма появятся в этой папке автоматически.</span></div>}{emails.map((m,i)=>{const a=m.from?.[0],unread=!m.keywords?.["$seen"];return <article onClick={()=>openMail(m)} className={(selected?.id===m.id?"selected ":"")+(unread?"unread":"")} key={m.id}><span className={"senderAvatar a"+((i%6)+1)}>{(a?.name||a?.email||"?")[0].toUpperCase()}</span><div className="msg"><div><b>{a?.name||a?.email||"Без отправителя"}</b><time>{m.receivedAt?new Date(m.receivedAt).toLocaleDateString("ru-RU",{day:"2-digit",month:"short"}):""}</time></div><strong>{m.subject||"(Без темы)"}</strong><p>{m.preview||""}</p>{m.hasAttachment&&<small className="tag"><Paperclip/> Вложение</small>}</div><button className="star" onClick={e=>{e.stopPropagation();action(m.keywords?.["$flagged"]?"unstar":"star",m.id)}}><Star fill={m.keywords?.["$flagged"]?"currentColor":"none"}/></button></article>})}</div></section>
  <section className={"reader "+(readerOpen?"mobileOpen":"")}><div className="toolbar"><div><button className="backReader" onClick={()=>setReaderOpen(false)}><ArrowLeft/></button>{selected&&<>{inTrash?<button onClick={()=>action("restore")} title="Восстановить"><Inbox/></button>:<button onClick={()=>action("archive")} title="Архив"><Archive/></button>}<button onClick={()=>action(inTrash?"delete":"trash")} title={inTrash?"Удалить навсегда":"В корзину"}><Trash2/></button><button onClick={()=>action(selected.keywords?.["$seen"]?"unread":"read")} title="Прочитано/непрочитано">{selected.keywords?.["$seen"]?<Mail/>:<MailOpen/>}</button></>}</div><div>{selected&&<><button onClick={()=>reply(false)}><Reply/></button><button><MoreHorizontal/></button></>}</div></div>
   {selected?<div className="letter"><div className="subjectLine"><div><h2>{selected.subject||"(Без темы)"}</h2></div><button className="favorite" onClick={()=>action(selected.keywords?.["$flagged"]?"unstar":"star")}><Star fill={selected.keywords?.["$flagged"]?"currentColor":"none"}/></button></div><div className="from"><span className="senderAvatar big">{(selected.from?.[0]?.name||selected.from?.[0]?.email||"?")[0].toUpperCase()}</span><div><b>{selected.from?.[0]?.name||selected.from?.[0]?.email}</b><small>{selected.from?.[0]?.email}</small></div><time>{selected.receivedAt?new Date(selected.receivedAt).toLocaleString("ru-RU"):""}</time></div><div className="body"><div className="mailText">{full?plainBody():"Загрузка письма…"}</div></div>{(full?.attachments||[]).map((a:any,i:number)=><div className="attachment" key={a.blobId||i}><div className="fileIcon"><Paperclip/></div><div><b>{a.name||"Вложение"}</b><small>{a.type||"Файл"}{a.size?" · "+Math.ceil(a.size/1024)+" КБ":""}</small></div><a className="attachmentDownload" href={"/api/mail/attachment?blobId="+encodeURIComponent(a.blobId)+"&name="+encodeURIComponent(a.name||"attachment")+"&type="+encodeURIComponent(a.type||"application/octet-stream")}>Скачать</a></div>)}<div className="actions"><button className="primary" onClick={()=>reply(false)}><Reply/>Ответить</button><button onClick={()=>reply(true)}>Переслать</button></div></div>:<div className="noSelection"><div><Mail/><h2>SchoolBook Mail</h2><p>Выберите письмо слева, чтобы прочитать его.</p></div></div>}
  </section></div>
  {compose&&<><div className="scrim" onClick={()=>setCompose(false)}/><div className="composeWindow"><div className="composeHead"><div><b>Новое сообщение</b><small>SchoolBook Mail</small></div><button onClick={()=>setCompose(false)}><X/></button></div><label><span>Кому</span><input autoFocus value={to} onChange={e=>setTo(e.target.value)} placeholder="email@example.com"/><button className="ccToggle" onClick={()=>setShowExtra(!showExtra)} type="button">Копия</button></label>{showExtra&&<><label><span>Копия</span><input value={cc} onChange={e=>setCc(e.target.value)} placeholder="cc@example.com"/></label><label><span>Скрытая</span><input value={bcc} onChange={e=>setBcc(e.target.value)} placeholder="bcc@example.com"/></label></>}<label><span>Тема</span><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Тема письма"/></label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Напишите сообщение…"/>{attachments.length>0&&<div className="composeFiles">{attachments.map((a:any,i:number)=><span key={i}><Paperclip/>{a.name}<button onClick={()=>setAttachments(x=>x.filter((_,n)=>n!==i))}><X/></button></span>)}</div>}{uploading&&<p className="composeStatus">Загрузка вложения…</p>}{sendError&&<p className="sendError">{sendError}</p>}<div className="composeFoot"><button className="send" onClick={sendMail} disabled={sending||uploading}><Send/>{sending?"Отправляем…":"Отправить"}</button><button onClick={()=>fileRef.current?.click()} title="Прикрепить"><Paperclip/></button><input ref={fileRef} hidden type="file" multiple onChange={e=>addFiles(e.target.files)}/><span/><button onClick={()=>{setCompose(false);resetCompose()}}><Trash2/></button></div></div></>}
 </main>
}