"use client";
import {FormEvent,useState} from "react";
import {ArrowRight,Eye,EyeOff,LockKeyhole,Mail} from "lucide-react";
import {useRouter} from "next/navigation";
import "./login.css";
export default function Login(){
 const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError("");setLoading(true);try{const r=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok){setError(d.error||"Ошибка входа");return}router.replace("/");router.refresh()}catch{setError("Сервер временно недоступен")}finally{setLoading(false)}}
 return <main className="loginPage"><section className="loginBrand"><div className="logo">S</div><div><b>SchoolBook</b><span>MAIL</span></div></section><section className="loginCard"><div className="loginIntro"><small>ДОБРО ПОЖАЛОВАТЬ</small><h1>Ваша почта.<br/>Просто и красиво.</h1><p>Войдите в свой почтовый аккаунт SchoolBook.</p></div><form onSubmit={submit}><label><span>Электронная почта</span><div><Mail/><input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@schoolbook.kg" required/></div></label><label><span>Пароль</span><div><LockKeyhole/><input type={show?"text":"password"} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Введите пароль" required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="loginError">{error}</p>}<button className="loginSubmit" disabled={loading}>{loading?"Входим…":<>Войти в почту <ArrowRight/></>}</button></form><footer>SchoolBook Mail · Защищённое соединение</footer></section></main>
}